/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  BreakdownCandidateOutput,  BreakdownMicroMotiveInput,  BreakdownMicroMotiveOutput,  DiscoveryActionKind,  DiscoveryContinuationInput,  DiscoveryMessage,  DiscoveryMethod,  DiscoveryStage,  DiscoverySuggestedAction,  DiscoveryTurn,  DiscoveryTurnKind,  FinalizeMicroMotiveInput,  MicroMotiveEvidence,  MicroMotiveOutput } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface BreakdownCandidateOutput {
      title?: string | null
      statement?: string | null
      why_it_might_fit?: string | null
      discovery_question?: string | null
    }
    export interface BreakdownMicroMotiveInput {
      title?: string | null
      statement?: string | null
      why_it_matters?: string | null
      boundary_conditions?: string | null
      evidence: MicroMotiveEvidence[]
    }
    export interface BreakdownMicroMotiveOutput {
      candidates: BreakdownCandidateOutput[]
    }
    export interface DiscoveryContinuationInput {
      current_stage?: types.DiscoveryStage | null
      messages: DiscoveryMessage[]
    }
    export interface DiscoveryMessage {
      role?: string | null
      content?: string | null
    }
    export interface DiscoverySuggestedAction {
      kind?: types.DiscoveryActionKind | null
      label?: string | null
    }
    export interface DiscoveryTurn {
      kind?: types.DiscoveryTurnKind | null
      method?: types.DiscoveryMethod | null
      stage?: types.DiscoveryStage | null
      reply?: string | null
      candidate?: string | null
      evidence_summary?: string | null
      suggested_action?: DiscoverySuggestedAction | null
    }
    export interface FinalizeMicroMotiveInput {
      accepted_statement?: string | null
      messages: DiscoveryMessage[]
      evidence_summary?: string | null
    }
    export interface MicroMotiveEvidence {
      situation?: string | null
      reaction?: string | null
      feelings: string[]
    }
    export interface MicroMotiveOutput {
      title?: string | null
      statement?: string | null
      why_it_matters?: string | null
      boundary_conditions?: string | null
      evidence: MicroMotiveEvidence[]
    }
}