/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;

    BreakdownCandidateOutput: ClassViewer<'BreakdownCandidateOutput', "title" | "statement" | "why_it_might_fit" | "discovery_question">;

    BreakdownMicroMotiveInput: ClassViewer<'BreakdownMicroMotiveInput', "title" | "statement" | "why_it_matters" | "boundary_conditions" | "evidence">;

    BreakdownMicroMotiveOutput: ClassViewer<'BreakdownMicroMotiveOutput', "candidates">;

    DiscoveryMessage: ClassViewer<'DiscoveryMessage', "role" | "content">;

    DiscoverySuggestedAction: ClassViewer<'DiscoverySuggestedAction', "kind" | "label">;

    DiscoveryTurn: ClassViewer<'DiscoveryTurn', "kind" | "reply" | "candidate" | "evidence_summary" | "suggested_action">;

    FinalizeMicroMotiveInput: ClassViewer<'FinalizeMicroMotiveInput', "accepted_statement" | "messages" | "evidence_summary">;

    MicroMotiveEvidence: ClassViewer<'MicroMotiveEvidence', "situation" | "reaction" | "feelings">;

    MicroMotiveOutput: ClassViewer<'MicroMotiveOutput', "title" | "statement" | "why_it_matters" | "boundary_conditions" | "evidence">;


    DiscoveryActionKind: EnumViewer<'DiscoveryActionKind', "SAVE_CANDIDATE">;

    DiscoveryTurnKind: EnumViewer<'DiscoveryTurnKind', "QUESTION" | "CANDIDATE">;


    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "BreakdownCandidateOutput","BreakdownMicroMotiveInput","BreakdownMicroMotiveOutput","DiscoveryMessage","DiscoverySuggestedAction","DiscoveryTurn","FinalizeMicroMotiveInput","MicroMotiveEvidence","MicroMotiveOutput",
          ]),
          enums: new Set([
            "DiscoveryActionKind","DiscoveryTurnKind",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });

        this.BreakdownCandidateOutput = this.tb.classViewer("BreakdownCandidateOutput", [
          "title","statement","why_it_might_fit","discovery_question",
        ]);

        this.BreakdownMicroMotiveInput = this.tb.classViewer("BreakdownMicroMotiveInput", [
          "title","statement","why_it_matters","boundary_conditions","evidence",
        ]);

        this.BreakdownMicroMotiveOutput = this.tb.classViewer("BreakdownMicroMotiveOutput", [
          "candidates",
        ]);

        this.DiscoveryMessage = this.tb.classViewer("DiscoveryMessage", [
          "role","content",
        ]);

        this.DiscoverySuggestedAction = this.tb.classViewer("DiscoverySuggestedAction", [
          "kind","label",
        ]);

        this.DiscoveryTurn = this.tb.classViewer("DiscoveryTurn", [
          "kind","reply","candidate","evidence_summary","suggested_action",
        ]);

        this.FinalizeMicroMotiveInput = this.tb.classViewer("FinalizeMicroMotiveInput", [
          "accepted_statement","messages","evidence_summary",
        ]);

        this.MicroMotiveEvidence = this.tb.classViewer("MicroMotiveEvidence", [
          "situation","reaction","feelings",
        ]);

        this.MicroMotiveOutput = this.tb.classViewer("MicroMotiveOutput", [
          "title","statement","why_it_matters","boundary_conditions","evidence",
        ]);


        this.DiscoveryActionKind = this.tb.enumViewer("DiscoveryActionKind", [
          "SAVE_CANDIDATE",
        ]);

        this.DiscoveryTurnKind = this.tb.enumViewer("DiscoveryTurnKind", [
          "QUESTION","CANDIDATE",
        ]);

    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.

    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}