/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum DiscoveryActionKind {
  SAVE_CANDIDATE = "SAVE_CANDIDATE",
}

export enum DiscoveryTurnKind {
  QUESTION = "QUESTION",
  CANDIDATE = "CANDIDATE",
}

export interface BreakdownCandidateOutput {
  title: string
  statement: string
  why_it_might_fit: string
  discovery_question: string

}

export interface BreakdownMicroMotiveInput {
  title: string
  statement: string
  why_it_matters: string
  boundary_conditions?: string | null
  evidence: MicroMotiveEvidence[]

}

export interface BreakdownMicroMotiveOutput {
  candidates: BreakdownCandidateOutput[]

}

export interface DiscoveryMessage {
  role: string
  content: string

}

export interface DiscoverySuggestedAction {
  kind: DiscoveryActionKind
  label: string

}

export interface DiscoveryTurn {
  kind: DiscoveryTurnKind
  reply: string
  candidate?: string | null
  evidence_summary?: string | null
  suggested_action?: DiscoverySuggestedAction | null

}

export interface FinalizeMicroMotiveInput {
  accepted_statement: string
  messages: DiscoveryMessage[]
  evidence_summary?: string | null

}

export interface MicroMotiveEvidence {
  situation: string
  reaction: string
  feelings: string[]

}

export interface MicroMotiveOutput {
  title: string
  statement: string
  why_it_matters: string
  boundary_conditions?: string | null
  evidence: MicroMotiveEvidence[]

}
